# Generated by Django 5.2.1 on 2025-05-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_review_rating_order_itemorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.ImageField(default='images/img.png', upload_to='images'),
        ),
    ]
