# Generated by Django 5.2.1 on 2025-05-31 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_book_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='itemorder',
            name='book',
        ),
        migrations.RemoveField(
            model_name='itemorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='ItemOrder',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
